# chapters
--embed-chapters

--embed-info-json
--write-description 
--embed-thumbnail  
# subs
--write-subs
--sub-lang en
--embed-subs
--write-auto-subs

# metadata
--embed-metadata 

# write metadata to file to be processed into an nfo
--write-info-json
-t mp4

# random sleep to avoid bans
--sleep-interval 5 
--max-sleep-interval 10

--ignore-errors
--no-overwrites

# filename to write
# -o "%(title)S.%(ext)s"

# restrict filenames to only ascii characters
--restrict-filenames